#!/usr/bin/env python3
"""Generate deterministic, self-contained OKF route-pack readers."""

from __future__ import annotations

import argparse
import html
import json
import os
import posixpath
import re
import sys
import urllib.parse
from pathlib import Path
from typing import Any


DOC_ROOT_PREFERENCES = ("docs", "documentation", "doc", "wiki", "manual", "manuals")
SIMILAR_DOC_TOKENS = ("doc", "wiki", "manual")
GENERATED_NOTICE = "<!-- Generated by tools/docs/build_okf_wikis.py; do not edit by hand. -->"
DOC_EXTENSIONS = {".md", ".card"}

DOC_ORDER = {
    "index.md": 0,
    "routing_guidance.card": 10,
    "routing.md": 20,
    "solution.md": 30,
    "architecture.md": 40,
    "data-model.md": 50,
    "operations.md": 60,
    "log.md": 90,
}


def norm_path(value: str) -> str:
    return value.strip().replace("\\", "/").lstrip("./")


def rel(repo: Path, value: str) -> Path:
    return repo / norm_path(value)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def find_manifest(repo: Path) -> Path:
    for root in DOC_ROOT_PREFERENCES:
        path = repo / root / "solutions.manifest.json"
        if path.exists():
            return path
    for path in sorted(repo.glob("*/solutions.manifest.json")):
        if any(token in path.parent.name.lower() for token in SIMILAR_DOC_TOKENS):
            return path
    raise FileNotFoundError("could not find solutions.manifest.json in a docs/documentation-like folder")


def solution_id(solution: dict[str, Any]) -> str:
    return str(solution["id"])


def solution_name(solution: dict[str, Any]) -> str:
    return str(solution.get("name") or solution.get("title") or solution["id"])


def solution_summary(solution: dict[str, Any]) -> str:
    return str(solution.get("summary") or solution.get("description") or "")


def solution_bundle(solution: dict[str, Any]) -> str:
    docs = solution.get("docs") or {}
    value = docs.get("root") or solution.get("bundle")
    if not value:
        raise KeyError(f"{solution_id(solution)} missing docs.root or bundle")
    return norm_path(str(value))


def solution_wiki(solution: dict[str, Any]) -> str:
    docs = solution.get("docs") or {}
    value = docs.get("wiki") or solution.get("wiki_html")
    if value:
        return norm_path(str(value))
    return f"{solution_bundle(solution).rstrip('/')}/wiki.html"


def solution_paths(solution: dict[str, Any]) -> list[str]:
    values = solution.get("owned_paths") or solution.get("routing_primary") or []
    return [norm_path(str(value)) for value in values if str(value).strip()]


def solution_keywords(solution: dict[str, Any]) -> list[str]:
    values = solution.get("routing_keywords") or []
    return [str(value).strip() for value in values if str(value).strip()]


def path_href(from_file: str, to_file: str) -> str:
    base = posixpath.dirname(norm_path(from_file))
    return posixpath.relpath(norm_path(to_file), base or ".")


def doc_sort_key(path: str) -> tuple[int, str]:
    name = posixpath.basename(path)
    return (DOC_ORDER.get(name, 80), path)


def load_bundle_docs(repo: Path, solution: dict[str, Any], *, with_virtual_index: bool = True) -> dict[str, str]:
    root = rel(repo, solution_bundle(solution))
    if not root.is_dir():
        raise FileNotFoundError(f"{solution_id(solution)} missing OKF bundle: {root}")

    docs: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix in DOC_EXTENSIONS:
            docs[path.relative_to(root).as_posix()] = read(path)

    if not docs:
        raise FileNotFoundError(f"{solution_id(solution)} has no OKF docs under {root}")
    if with_virtual_index and "index.md" not in docs:
        docs["index.md"] = solution_index_doc(solution, docs)
    return dict(sorted(docs.items(), key=lambda item: doc_sort_key(item[0])))


def solution_index_doc(solution: dict[str, Any], docs: dict[str, str]) -> str:
    paths = solution_paths(solution)
    keywords = solution_keywords(solution)
    tags = ["okf", "solution"]
    links = [f"- [{display_title(path, {}, text)}]({path})" for path, text in sorted(docs.items(), key=lambda item: doc_sort_key(item[0]))]
    lines = [
        "---",
        "type: SolutionIndex",
        f"title: {json.dumps(solution_name(solution) + ' OKF Bundle')}",
        f"description: {json.dumps(solution_summary(solution))}",
        "tags: [" + ", ".join(tags) + "]",
    ]
    if paths:
        lines.append("routing_primary:")
        lines.extend(f"- {path}" for path in paths)
    if keywords:
        lines.append("routing_keywords:")
        lines.extend(f"- {keyword}" for keyword in keywords)
    lines.extend([
        "---",
        "",
        f"# {solution_name(solution)} OKF Bundle",
        "",
        solution_summary(solution),
        "",
        "## Pages",
        "",
        *links,
        "",
    ])
    return "\n".join(lines)


def umbrella_docs(manifest: dict[str, Any], repo: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    entries: list[tuple[str, str, str, str]] = []
    for solution in manifest.get("solutions", []):
        sid = solution_id(solution)
        bundle_docs = load_bundle_docs(repo, solution, with_virtual_index=True)
        preferred = "solution.md" if "solution.md" in bundle_docs else "index.md"
        entries.append((sid, solution_name(solution), solution_summary(solution), f"solutions/{sid}/{preferred}"))
        for path, text in bundle_docs.items():
            docs[f"solutions/{sid}/{path}"] = text

    title = str((manifest.get("wiki") or {}).get("title") or "OKF Route Pack")
    lines = [
        "---",
        'okf_version: "1.0"',
        "type: KnowledgeBundle",
        f"title: {json.dumps(title)}",
        "description: Umbrella index for OKF solution bundles.",
        "tags: [okf, umbrella]",
        "---",
        "",
        "# OKF Route Pack Index",
        "",
    ]
    for _sid, name, summary, target in sorted(entries, key=lambda item: item[1].lower()):
        suffix = f" - {summary}" if summary else ""
        lines.append(f"- [{name}]({target}){suffix}")
    docs["index.md"] = "\n".join(lines) + "\n"
    return dict(sorted(docs.items(), key=lambda item: doc_sort_key(item[0])))


def generated_index_md(manifest: dict[str, Any]) -> str:
    wiki = manifest.get("wiki") or {}
    index_path = norm_path(str(wiki.get("index") or f"{wiki.get('root', 'docs/okf')}/index.md"))
    lines = ["# OKF Route Pack Index", ""]
    for solution in manifest.get("solutions", []):
        target = path_href(index_path, solution_wiki(solution))
        summary = solution_summary(solution)
        suffix = f" - {summary}" if summary else ""
        lines.append(f"- [{solution_name(solution)}]({target}){suffix}")
    return "\n".join(lines) + "\n"


def expected_outputs(repo: Path, manifest: dict[str, Any]) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for solution in manifest.get("solutions", []):
        docs = load_bundle_docs(repo, solution, with_virtual_index=True)
        html_text, _stats = generate_html(
            bundle_name=f"{solution_name(solution)} OKF Route Pack",
            docs_by_path=docs,
            manifest=manifest,
            current_solution=solution,
            render_mode="per-solution",
        )
        outputs[rel(repo, solution_wiki(solution))] = html_text

    wiki = manifest.get("wiki") or {}
    index_path = norm_path(str(wiki.get("index") or f"{wiki.get('root', 'docs/okf')}/index.md"))
    umbrella_path = norm_path(str(wiki.get("umbrella") or "docs/wiki.html"))
    outputs[rel(repo, index_path)] = generated_index_md(manifest)
    umbrella_html, _stats = generate_html(
        bundle_name=str(wiki.get("title") or "OKF Route Pack"),
        docs_by_path=umbrella_docs(manifest, repo),
        manifest=manifest,
        current_solution=None,
        render_mode="umbrella",
    )
    outputs[rel(repo, umbrella_path)] = umbrella_html
    return outputs


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text

    metadata: dict[str, Any] = {}
    lines = text[4:end].splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in line:
            index += 1
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value:
            metadata[key] = parse_frontmatter_value(value)
            index += 1
            continue
        items: list[str] = []
        index += 1
        while index < len(lines):
            child = lines[index]
            child_stripped = child.strip()
            if not child_stripped or child_stripped.startswith("#"):
                index += 1
                continue
            if not child.startswith((" ", "\t")) and not child_stripped.startswith("- "):
                break
            match = re.match(r"^\s*-\s+(.+)$", child)
            if match:
                items.append(unquote(match.group(1).strip()))
            index += 1
        metadata[key] = items
    return metadata, text[end + len("\n---\n") :]


def parse_frontmatter_value(value: str) -> Any:
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [unquote(part.strip()) for part in inner.split(",")]
    try:
        parsed = json.loads(value)
        if isinstance(parsed, (str, int, float, bool, list)):
            return parsed
    except json.JSONDecodeError:
        pass
    return unquote(value)


def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def display_title(rel_path: str, metadata: dict[str, Any], body: str) -> str:
    title = metadata.get("title")
    if isinstance(title, str) and title.strip():
        return title.strip()
    for line in body.splitlines():
        match = re.match(r"^#\s+(.+)$", line.strip())
        if match:
            return strip_markdown(match.group(1)).strip() or rel_path
    return Path(rel_path).stem.replace("-", " ").replace("_", " ").title()


def strip_leading_title_heading(body: str, title: str) -> str:
    lines = body.splitlines()
    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index >= len(lines):
        return body
    match = re.match(r"^#\s+(.+)$", lines[index].strip())
    if not match:
        return body
    if strip_markdown(match.group(1)).strip().casefold() != title.strip().casefold():
        return body
    return "\n".join(lines[index + 1 :]).lstrip("\n")


def display_description(metadata: dict[str, Any]) -> str:
    value = metadata.get("description")
    return value.strip() if isinstance(value, str) else ""


def display_type(rel_path: str, metadata: dict[str, Any]) -> str:
    value = metadata.get("type")
    if isinstance(value, str) and value.strip():
        return value.strip()
    name = posixpath.basename(rel_path)
    if rel_path == "index.md" or name == "index.md":
        return "Index"
    if name == "routing_guidance.card":
        return "RoutingCard"
    if name == "routing.md":
        return "RoutingGuide"
    if name == "solution.md":
        return "SolutionGuide"
    if name == "log.md":
        return "Log"
    return "Concept"


def display_tags(metadata: dict[str, Any]) -> list[str]:
    value = metadata.get("tags")
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def metadata_search_terms(metadata: dict[str, Any]) -> list[str]:
    terms: list[str] = []
    for key, value in metadata.items():
        if key in {"title", "description", "tags", "timestamp"}:
            continue
        terms.append(key)
        if isinstance(value, list):
            terms.extend(str(item) for item in value)
        elif isinstance(value, str):
            terms.append(value)
    return terms


def strip_markdown(value: str) -> str:
    value = re.sub(r"`([^`]+)`", r"\1", value)
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"[*_#>]+", "", value)
    return value


def collect_internal_links(rel_path: str, body: str, docs_by_path: dict[str, str]) -> list[str]:
    targets: set[str] = set()
    for match in re.finditer(r"(?<!!)\[[^\]]+\]\(([^)]+)\)", body):
        resolved = resolve_bundle_link(rel_path, match.group(1).strip(), docs_by_path)
        if resolved is not None and resolved != rel_path:
            targets.add(resolved)
    return sorted(targets)


def resolve_bundle_link(rel_path: str, raw_target: str, docs_by_path: dict[str, str]) -> str | None:
    target, _fragment = split_fragment(raw_target)
    decoded = urllib.parse.unquote(target).strip()
    if is_external(decoded):
        return None

    if not decoded:
        candidate = rel_path
    elif decoded.startswith("/"):
        candidate = posixpath.normpath(decoded.lstrip("/"))
    else:
        candidate = posixpath.normpath(posixpath.join(posixpath.dirname(rel_path), decoded))

    if candidate in {"", "."}:
        candidate = "index.md"
    if candidate.endswith("/"):
        candidate = posixpath.join(candidate, "index.md")
    candidates = [
        candidate,
        posixpath.join(candidate, "index.md"),
        posixpath.join(candidate, "README.md"),
    ]
    for item in candidates:
        if item in docs_by_path:
            return item
    return None


def parse_cross_link(raw_target: str) -> tuple[str, str] | None:
    target, _fragment = split_fragment(raw_target)
    decoded = urllib.parse.unquote(target).strip()
    match = re.match(r"^\.\./([^/]+)/(.+)$", decoded)
    if match:
        return match.group(1), match.group(2)
    return None


def resolve_cross_link(
    raw_target: str,
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> str | None:
    parsed = parse_cross_link(raw_target)
    if parsed is None or manifest is None:
        return None
    peer_id, page = parsed
    peer = next((item for item in manifest.get("solutions", []) if solution_id(item) == peer_id), None)
    if peer is None:
        return None
    _target, fragment = split_fragment(raw_target)
    anchor_part = f"#{urllib.parse.quote(fragment, safe='-_.~')}" if fragment else ""
    encoded_page = urllib.parse.quote(page, safe="/-_.~")
    if render_mode == "umbrella":
        return f"#doc/solutions/{peer_id}/{encoded_page}{anchor_part}"
    if current_solution is None:
        return None
    current_dir = posixpath.dirname(solution_wiki(current_solution))
    rel_html = os.path.relpath(solution_wiki(peer), current_dir).replace("\\", "/")
    return f"{rel_html}#doc/{encoded_page}{anchor_part}"


def split_fragment(raw_target: str) -> tuple[str, str]:
    target, separator, fragment = raw_target.partition("#")
    return target, fragment if separator else ""


def is_external(target: str) -> bool:
    return bool(re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target)) or target.startswith("mailto:")


def markdown_to_html(
    markdown: str,
    rel_path: str,
    docs_by_path: dict[str, str],
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> str:
    lines = markdown.splitlines()
    out: list[str] = []
    paragraph: list[str] = []
    list_stack: list[str] = []
    in_code = False
    code_lines: list[str] = []
    code_language = ""
    heading_counts: dict[str, int] = {}
    quote_lines: list[str] = []
    index = 0

    def close_paragraph() -> None:
        if paragraph:
            text = " ".join(part.strip() for part in paragraph).strip()
            if text:
                out.append(f"<p>{render_inline(text, rel_path, docs_by_path, manifest, current_solution, render_mode)}</p>")
            paragraph.clear()

    def close_lists() -> None:
        close_paragraph()
        while list_stack:
            out.append(f"</{list_stack.pop()}>")

    def close_quote() -> None:
        if quote_lines:
            quote_text = "\n".join(quote_lines)
            out.append(
                "<blockquote>"
                + markdown_to_html(quote_text, rel_path, docs_by_path, manifest, current_solution, render_mode)
                + "</blockquote>"
            )
            quote_lines.clear()

    def close_all() -> None:
        close_paragraph()
        close_quote()
        close_lists()

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        fence = re.match(r"^```\s*([^`]*)$", stripped)
        if fence:
            if in_code:
                language_attr = f" class=\"language-{html.escape(code_language)}\"" if code_language else ""
                out.append(f"<pre><code{language_attr}>{html.escape(chr(10).join(code_lines))}</code></pre>")
                code_lines.clear()
                code_language = ""
                in_code = False
            else:
                close_all()
                code_language = fence.group(1).strip()
                in_code = True
            index += 1
            continue

        if in_code:
            code_lines.append(line)
            index += 1
            continue

        if not stripped:
            close_paragraph()
            close_quote()
            close_lists()
            index += 1
            continue

        table_end = table_block_end(lines, index)
        if table_end is not None:
            close_all()
            out.append(render_table(lines[index:table_end], rel_path, docs_by_path, manifest, current_solution, render_mode))
            index = table_end
            continue

        heading = re.match(r"^(#{1,6})\s+(.+)$", stripped)
        if heading:
            close_all()
            level = len(heading.group(1))
            raw_title = heading.group(2).strip()
            anchor = unique_anchor(slugify(strip_markdown(raw_title)), heading_counts)
            out.append(
                f"<h{level} id=\"{html.escape(anchor)}\">"
                f"{render_inline(raw_title, rel_path, docs_by_path, manifest, current_solution, render_mode)}</h{level}>"
            )
            index += 1
            continue

        if re.fullmatch(r"([-*_])(?:\s*\1){2,}\s*", stripped):
            close_all()
            out.append("<hr />")
            index += 1
            continue

        if stripped.startswith(">"):
            close_paragraph()
            close_lists()
            quote_lines.append(stripped[1:].lstrip())
            index += 1
            continue

        bullet = re.match(r"^[-*+]\s+(.+)$", stripped)
        numbered = re.match(r"^\d+[.)]\s+(.+)$", stripped)
        if bullet or numbered:
            close_paragraph()
            close_quote()
            kind = "ul" if bullet else "ol"
            if not list_stack or list_stack[-1] != kind:
                close_lists()
                list_stack.append(kind)
                out.append(f"<{kind}>")
            item_parts = [(bullet or numbered).group(1)]
            index += 1
            while index < len(lines):
                peek = lines[index].strip()
                if (
                    not peek
                    or re.match(r"^[-*+]\s+", peek)
                    or re.match(r"^\d+[.)]\s+", peek)
                    or re.match(r"^#{1,6}\s+", peek)
                    or peek.startswith("```")
                    or peek.startswith(">")
                    or re.fullmatch(r"([-*_])(?:\s*\1){2,}\s*", peek)
                    or ("|" in peek and table_block_end(lines, index) is not None)
                ):
                    break
                item_parts.append(peek)
                index += 1
            item_text = " ".join(part.strip() for part in item_parts if part.strip())
            out.append(f"<li>{render_inline(item_text, rel_path, docs_by_path, manifest, current_solution, render_mode)}</li>")
            continue

        close_quote()
        paragraph.append(line)
        index += 1

    if in_code:
        language_attr = f" class=\"language-{html.escape(code_language)}\"" if code_language else ""
        out.append(f"<pre><code{language_attr}>{html.escape(chr(10).join(code_lines))}</code></pre>")
    close_all()
    return "\n".join(out)


def table_block_end(lines: list[str], start: int) -> int | None:
    if start + 1 >= len(lines):
        return None
    first = lines[start].strip()
    second = lines[start + 1].strip()
    if "|" not in first or "|" not in second:
        return None
    if not re.fullmatch(r"\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?", second):
        return None
    end = start + 2
    while end < len(lines) and "|" in lines[end].strip() and lines[end].strip():
        end += 1
    return end


def render_table(
    lines: list[str],
    rel_path: str,
    docs_by_path: dict[str, str],
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> str:
    header = split_table_row(lines[0])
    body_rows = [split_table_row(line) for line in lines[2:]]
    parts = ["<table>", "<thead><tr>"]
    for cell in header:
        parts.append(f"<th>{render_inline(cell, rel_path, docs_by_path, manifest, current_solution, render_mode)}</th>")
    parts.append("</tr></thead>")
    if body_rows:
        parts.append("<tbody>")
        for row in body_rows:
            parts.append("<tr>")
            for cell in row:
                parts.append(f"<td>{render_inline(cell, rel_path, docs_by_path, manifest, current_solution, render_mode)}</td>")
            parts.append("</tr>")
        parts.append("</tbody>")
    parts.append("</table>")
    return "\n".join(parts)


def split_table_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def unique_anchor(base: str, counts: dict[str, int]) -> str:
    base = base or "section"
    counts[base] = counts.get(base, 0) + 1
    return base if counts[base] == 1 else f"{base}-{counts[base] - 1}"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[`*_{}\[\]()<>=!#\"\\]", "", value)
    value = re.sub(r"[^a-z0-9 _.-]+", "", value)
    return re.sub(r"\s+", "-", value).strip("-")


def render_inline(
    text: str,
    rel_path: str,
    docs_by_path: dict[str, str],
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> str:
    code_tokens: dict[str, str] = {}

    def save_code(match: re.Match[str]) -> str:
        token = f"\x00CODE{len(code_tokens)}\x00"
        code_tokens[token] = f"<code>{html.escape(match.group(1))}</code>"
        return token

    protected = re.sub(r"`([^`]+)`", save_code, text)
    rendered = render_links(protected, rel_path, docs_by_path, manifest, current_solution, render_mode)
    for token, html_code in code_tokens.items():
        rendered = rendered.replace(token, html_code)
    return rendered


def render_links(
    text: str,
    rel_path: str,
    docs_by_path: dict[str, str],
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> str:
    pieces: list[str] = []
    cursor = 0
    pattern = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
    for match in pattern.finditer(text):
        pieces.append(render_inline_text(text[cursor : match.start()]))
        label = render_inline_text(strip_markdown(match.group(1)))
        raw_target = match.group(2).strip()
        _target, fragment = split_fragment(raw_target)
        resolved = resolve_bundle_link(rel_path, raw_target, docs_by_path)
        if resolved is None:
            cross_href = resolve_cross_link(raw_target, manifest, current_solution, render_mode)
            href = cross_href if cross_href is not None else raw_target
            pieces.append(f"<a href=\"{html.escape(href, quote=True)}\">{label}</a>")
        else:
            anchor_part = f"#{urllib.parse.quote(fragment, safe='-_.~')}" if fragment else ""
            href_target = urllib.parse.quote(resolved, safe="/-_.~")
            href = f"#doc/{href_target}{anchor_part}"
            pieces.append(
                f"<a href=\"{html.escape(href, quote=True)}\" "
                f"data-doc-link=\"{html.escape(resolved, quote=True)}\" "
                f"data-doc-anchor=\"{html.escape(fragment, quote=True)}\">{label}</a>"
            )
        cursor = match.end()
    pieces.append(render_inline_text(text[cursor:]))
    return "".join(pieces)


def render_inline_text(text: str) -> str:
    escaped = html.escape(text)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"__([^_]+)__", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", escaped)
    escaped = re.sub(r"(?<!_)_([^_]+)_(?!_)", r"<em>\1</em>", escaped)
    return escaped


def generate_html(
    *,
    bundle_name: str,
    docs_by_path: dict[str, str],
    manifest: dict[str, Any] | None,
    current_solution: dict[str, Any] | None,
    render_mode: str,
) -> tuple[str, dict[str, int]]:
    documents: list[dict[str, Any]] = []
    links: list[dict[str, str]] = []
    for path, raw in sorted(docs_by_path.items(), key=lambda item: doc_sort_key(item[0])):
        metadata, body = parse_frontmatter(raw)
        title = display_title(path, metadata, body)
        description = display_description(metadata)
        doc_type = display_type(path, metadata)
        tags = display_tags(metadata)
        outgoing = collect_internal_links(path, body, docs_by_path)
        for target in outgoing:
            links.append({"source": path, "target": target})
        documents.append(
            {
                "path": path,
                "title": title,
                "description": description,
                "type": doc_type,
                "tags": tags,
                "metadata": metadata,
                "html": markdown_to_html(
                    strip_leading_title_heading(body, title),
                    path,
                    docs_by_path,
                    manifest,
                    current_solution,
                    render_mode,
                ),
                "outgoing": outgoing,
                "search": " ".join([path, title, description, doc_type, *tags, *metadata_search_terms(metadata)]).lower(),
            }
        )

    backlinks: dict[str, list[str]] = {doc["path"]: [] for doc in documents}
    for link in links:
        backlinks.setdefault(link["target"], []).append(link["source"])
    for values in backlinks.values():
        values.sort()

    bundle = {
        "name": bundle_name,
        "docs": documents,
        "links": links,
        "backlinks": backlinks,
        "stats": {"docs": len(documents), "links": len(links)},
    }
    data_json = json.dumps(bundle, ensure_ascii=False, indent=2, sort_keys=True).replace("</", "<\\/")
    output = HTML_TEMPLATE.replace("@@BUNDLE_NAME@@", html.escape(bundle_name)).replace("@@DATA_JSON@@", data_json)
    output = f"{GENERATED_NOTICE}\n{output}"
    return output, {"docs": len(documents), "links": len(links), "bytes": len(output.encode("utf-8"))}


def smoke_html(path: Path, content: str) -> None:
    lowered = content.lower()
    required = [
        "<!doctype html>",
        'id="okf-data"',
        'id="doclist"',
        'id="article"',
        "single-file okf reader",
    ]
    missing = [item for item in required if item not in lowered]
    if missing:
        raise RuntimeError(f"bad html output {path}: missing {', '.join(missing)}")
    match = re.search(r'<script id="okf-data" type="application/json">\s*(.*?)\s*</script>', content, re.S)
    if not match:
        raise RuntimeError(f"bad html output {path}: missing OKF JSON payload")
    payload = json.loads(match.group(1))
    if not payload.get("docs"):
        raise RuntimeError(f"bad html output {path}: no documents in OKF JSON payload")
    if payload.get("stats", {}).get("links", 0) <= 0:
        raise RuntimeError(f"bad html output {path}: no internal links in OKF JSON payload")


def write_outputs(repo: Path, outputs: dict[Path, str], *, check: bool, browser_smoke: bool) -> int:
    stale: list[str] = []
    for path, content in outputs.items():
        if browser_smoke and path.suffix == ".html":
            smoke_html(path, content)
        if check:
            if not path.exists() or read(path) != content:
                stale.append(str(path.relative_to(repo)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("OKF generated files are stale:")
        for item in stale:
            print(f"- {item}")
        return 1
    return 0


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>@@BUNDLE_NAME@@</title>
<style>
:root {
  color-scheme: light dark;
  --bg: #f5f7fa;
  --panel: #ffffff;
  --panel-muted: #eef2f7;
  --text: #172033;
  --muted: #5f6c7b;
  --accent: #2563eb;
  --accent-strong: #1d4ed8;
  --border: #d8dee8;
  --code-bg: #edf2f7;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #111827;
    --panel: #1f2937;
    --panel-muted: #273449;
    --text: #f3f4f6;
    --muted: #a7b0bf;
    --accent: #93c5fd;
    --accent-strong: #bfdbfe;
    --border: #374151;
    --code-bg: #273449;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.55;
  color: var(--text);
  background: var(--bg);
}
a { color: var(--accent); }
a:hover { color: var(--accent-strong); }
.app {
  display: grid;
  grid-template-columns: minmax(18rem, 24rem) minmax(0, 1fr);
  min-height: 100vh;
}
.sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
  padding: 1rem;
  border-right: 1px solid var(--border);
  background: var(--panel);
}
.brand h1 { margin: 0; font-size: 1.15rem; }
.brand p, .meta, .empty, .source-link { color: var(--muted); font-size: 0.9rem; }
.controls { display: grid; gap: 0.65rem; margin: 1rem 0; }
input, select {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 0.5rem;
  padding: 0.65rem 0.75rem;
  color: var(--text);
  background: var(--panel);
}
.doc-list { display: grid; gap: 0.45rem; }
.doc-link {
  display: block;
  padding: 0.65rem 0.7rem;
  border: 1px solid transparent;
  border-radius: 0.5rem;
  color: var(--text);
  text-decoration: none;
}
.doc-link:hover, .doc-link.active { border-color: var(--border); background: var(--panel-muted); }
.doc-link strong { display: block; font-size: 0.95rem; }
.doc-link span { display: block; color: var(--muted); font-size: 0.78rem; }
.main { min-width: 0; padding: clamp(1rem, 3vw, 2.5rem); }
.article-shell {
  max-width: 78rem;
  margin: 0 auto;
  padding: clamp(1rem, 4vw, 3rem);
  border: 1px solid var(--border);
  border-radius: 0.75rem;
  background: var(--panel);
}
.article-header {
  display: grid;
  gap: 0.4rem;
  padding-bottom: 1.25rem;
  border-bottom: 1px solid var(--border);
  margin-bottom: 1.5rem;
}
.article-header h2 { margin: 0; font-size: clamp(1.8rem, 5vw, 3rem); line-height: 1.1; }
.badges, .link-row { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.badge, .pill {
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  border: 1px solid var(--border);
  padding: 0.2rem 0.55rem;
  background: var(--panel-muted);
  color: var(--muted);
  font-size: 0.78rem;
}
.article-body h1, .article-body h2, .article-body h3 { line-height: 1.2; margin-top: 1.6em; }
.article-body h1:first-child { margin-top: 0; }
.article-body pre {
  overflow: auto;
  padding: 1rem;
  border-radius: 0.5rem;
  background: var(--code-bg);
}
.article-body code { border-radius: 0.25rem; padding: 0.1rem 0.25rem; background: var(--code-bg); }
.article-body pre code { padding: 0; background: transparent; }
.article-body table { width: 100%; border-collapse: collapse; overflow: auto; display: block; }
.article-body th, .article-body td { border: 1px solid var(--border); padding: 0.45rem 0.55rem; vertical-align: top; }
.article-body blockquote {
  margin: 1rem 0;
  padding: 0.25rem 1rem;
  border-left: 0.25rem solid var(--accent);
  color: var(--muted);
  background: var(--panel-muted);
}
.relationships { display: grid; gap: 0.75rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }
.relationships h3 { margin: 0; }
.routing-panel {
  margin-top: 1rem;
  padding: 1rem;
  border: 1px solid var(--border);
  border-radius: 0.65rem;
  background: var(--panel-muted);
}
.routing-panel h3 { margin: 0 0 0.65rem; }
.routing-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); gap: 0.85rem; }
.route-list { margin: 0.35rem 0 0; padding-left: 1.1rem; }
.route-list li { margin: 0.2rem 0; }
.route-list code { overflow-wrap: anywhere; }
@media (max-width: 860px) {
  .app { grid-template-columns: 1fr; }
  .sidebar { position: static; height: auto; max-height: 55vh; border-right: 0; border-bottom: 1px solid var(--border); }
}
</style>
</head>
<body>
<div class="app">
  <aside class="sidebar" aria-label="Wiki navigation">
    <div class="brand">
      <h1>@@BUNDLE_NAME@@</h1>
      <p id="stats"></p>
    </div>
    <div class="controls">
      <label>
        <span class="meta">Search title, path, tags, summary, and routing</span>
        <input id="search" type="search" placeholder="Search route pack..." autocomplete="off" />
      </label>
      <label>
        <span class="meta">Filter by OKF type</span>
        <select id="typeFilter"><option value="">All types</option></select>
      </label>
    </div>
    <nav id="docList" class="doc-list"></nav>
  </aside>
  <main class="main">
    <article class="article-shell" id="article"></article>
  </main>
</div>
<script id="okf-data" type="application/json">
@@DATA_JSON@@
</script>
<script>
(() => {
  "use strict";
  const bundle = JSON.parse(document.getElementById("okf-data").textContent);
  const docs = bundle.docs;
  const docsByPath = new Map(docs.map((doc) => [doc.path, doc]));
  const article = document.getElementById("article");
  const docList = document.getElementById("docList");
  const search = document.getElementById("search");
  const typeFilter = document.getElementById("typeFilter");
  const stats = document.getElementById("stats");

  stats.textContent = `${bundle.stats.docs} docs - ${bundle.stats.links} internal links - single-file OKF reader`;

  for (const type of [...new Set(docs.map((doc) => doc.type))].sort((a, b) => a.localeCompare(b))) {
    const option = document.createElement("option");
    option.value = type;
    option.textContent = type;
    typeFilter.appendChild(option);
  }

  function parseHash() {
    const hash = decodeURIComponent(window.location.hash || "");
    if (!hash.startsWith("#doc/")) return { path: "index.md", anchor: "" };
    const payload = hash.slice(5);
    const split = payload.indexOf("#");
    if (split < 0) return { path: payload || "index.md", anchor: "" };
    return { path: payload.slice(0, split) || "index.md", anchor: payload.slice(split + 1) };
  }

  function docHref(path, anchor = "") {
    const encoded = encodeURIComponent(path).replace(/%2F/g, "/");
    return `#doc/${encoded}${anchor ? `#${encodeURIComponent(anchor)}` : ""}`;
  }

  function escapeHtml(value) {
    return String(value ?? "").replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;"
    }[ch]));
  }

  function renderList() {
    const needle = search.value.trim().toLowerCase();
    const selectedType = typeFilter.value;
    const { path: activePath } = parseHash();
    const filtered = docs.filter((doc) => {
      return (!selectedType || doc.type === selectedType) && (!needle || doc.search.includes(needle));
    });
    docList.innerHTML = filtered.map((doc) => `
      <a class="doc-link ${doc.path === activePath ? "active" : ""}" href="${docHref(doc.path)}">
        <strong>${escapeHtml(doc.title)}</strong>
        <span>${escapeHtml(doc.path)} - ${escapeHtml(doc.type)}</span>
      </a>
    `).join("") || `<p class="empty">No matching route-pack pages.</p>`;
  }

  function linkPills(paths, emptyText) {
    if (!paths || paths.length === 0) return `<p class="empty">${escapeHtml(emptyText)}</p>`;
    return `<div class="link-row">${paths.map((path) => {
      const doc = docsByPath.get(path);
      const label = doc ? doc.title : path;
      return `<a class="pill" href="${docHref(path)}">${escapeHtml(label)}</a>`;
    }).join("")}</div>`;
  }

  function listValue(value) {
    if (Array.isArray(value)) return value.filter((item) => String(item || "").trim());
    if (typeof value === "string" && value.trim()) return [value.trim()];
    return [];
  }

  function renderRouteList(label, values) {
    if (!values.length) return "";
    return `
      <section>
        <strong>${escapeHtml(label)}</strong>
        <ul class="route-list">
          ${values.map((value) => `<li><code>${escapeHtml(value)}</code></li>`).join("")}
        </ul>
      </section>
    `;
  }

  function renderRouting(metadata) {
    const sections = [
      renderRouteList("Start here", listValue(metadata.routing_primary)),
      renderRouteList("Usually also inspect", listValue(metadata.routing_related)),
      renderRouteList("Keywords", listValue(metadata.routing_keywords)),
      renderRouteList("Runbooks / references", listValue(metadata.routing_runbooks))
    ].filter(Boolean);
    if (!sections.length) return "";
    return `
      <section class="routing-panel" aria-label="Agent routing">
        <h3>Agent routing</h3>
        <div class="routing-grid">${sections.join("")}</div>
      </section>
    `;
  }

  function renderArticle() {
    const { path, anchor } = parseHash();
    const doc = docsByPath.get(path) || docsByPath.get("index.md") || docs[0];
    if (!doc) {
      article.innerHTML = `<h2>No wiki documents found</h2>`;
      return;
    }
    document.title = `${doc.title} - ${bundle.name}`;
    const tagBadges = (doc.tags || []).map((tag) => `<span class="badge">#${escapeHtml(tag)}</span>`).join("");
    const metadata = Object.entries(doc.metadata || {})
      .filter(([key]) => !["title", "description", "tags"].includes(key) && !key.startsWith("routing_"))
      .map(([key, value]) => `<span class="badge">${escapeHtml(key)}: ${escapeHtml(Array.isArray(value) ? value.join(", ") : value)}</span>`)
      .join("");
    article.innerHTML = `
      <header class="article-header">
        <div class="badges"><span class="badge">${escapeHtml(doc.type)}</span>${tagBadges}${metadata}</div>
        <h2>${escapeHtml(doc.title)}</h2>
        ${doc.description ? `<p>${escapeHtml(doc.description)}</p>` : ""}
        <div class="source-link">Source path: ${escapeHtml(doc.path)}</div>
        ${renderRouting(doc.metadata || {})}
      </header>
      <section class="article-body">${doc.html}</section>
      <section class="relationships" aria-label="OKF relationships">
        <h3>Links from this page</h3>
        ${linkPills(doc.outgoing, "No internal OKF links from this page.")}
        <h3>Cited by</h3>
        ${linkPills(bundle.backlinks[doc.path] || [], "No other route-pack page links here yet.")}
      </section>
    `;
    renderList();
    if (anchor) {
      requestAnimationFrame(() => {
        const target = document.getElementById(anchor);
        if (target) target.scrollIntoView({ block: "start" });
      });
    }
  }

  document.addEventListener("click", (event) => {
    const link = event.target.closest("a[data-doc-link]");
    if (!link) return;
    event.preventDefault();
    window.location.hash = docHref(link.dataset.docLink, link.dataset.docAnchor || "");
  });
  search.addEventListener("input", renderList);
  typeFilter.addEventListener("change", renderList);
  window.addEventListener("hashchange", renderArticle);
  renderList();
  renderArticle();
})();
</script>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate OKF route-pack readers.")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--manifest")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--browser-smoke", action="store_true")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    manifest_path = Path(args.manifest).resolve() if args.manifest else find_manifest(repo)
    manifest = json.loads(read(manifest_path))
    outputs = expected_outputs(repo, manifest)
    status = write_outputs(repo, outputs, check=args.check, browser_smoke=args.browser_smoke)
    if status:
        return status
    print("OKF route-pack build check passed." if args.check else "OKF route-pack build complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
